platform :ios, '9.0'
use_frameworks!

post_install do |installer|
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
end

post_install do |installer|
    `rm -rf Pods/Headers/Private`
    `find Pods -regex 'Pods\/.*\.modulemap' -print0 | xargs -0 sed -i '' 's/private header.*/'`
end



target 'BenjaminWernsman-HW7' do
  pod 'Alamofire', '~> 3.0'
  pod 'SwiftyJSON', '2.4.0'
end


